# This document aims to be a complete list of all valuable phonetic kanji components sourced
# from Habein & Mathias' "The Complete Guide to Everyday Kanji." The book is a trove of information, 
# this seeks to distill it down to only the information useful to a student of Japanese.
# this list is very much a WORK IN PROGRESS and does not nearly cover everything, but I hope to complete the phonetic component at minimum.

#TEMPLATES
# [[useful]]
# component = ""
# used_in = ["", "", ""]
# not_useful_in = []
# readings = [""]

# [[non-useful]]
# component = ""
# used_in = ["", ""]
# reason = ""

#  ____ _____  _    ____ _____    ___  _____   _     ___ ____ _____
# / ___|_   _|/ \  |  _ \_   _|  / _ \|  ___| | |   |_ _/ ___|_   _|
# \___ \ | | / _ \ | |_) || |   | | | | |_    | |    | |\___ \ | |
#  ___) || |/ ___ \|  _ < | |   | |_| |  _|   | |___ | | ___) || |
# |____/ |_/_/   \_\_| \_\|_|    \___/|_|     |_____|___|____/ |_|

# 1-Stroke
[[non-useful]]
component = "乙"
used_in = ["礼"]
reason = "only 1 kanji"

# 2-Stroke
[[useful]]
component = "又"
used_in = ["受", "授"]
readings = ["ジュ"]

[[non-useful]]
component = "九"
used_in = ["究, 軌"]
reason = "poor reading agreement."

[[useful]]
component = "七"
used_in = ["切", "窃"]
readings = ["セツ"]

[[non-useful]]
component = "十"
used_in = ["汁", "針"]
reason = "poor reading agreement"

[[useful]]
component = "丁"
used_in = ["庁", "成", "町", "亭", "頂", "城", "盛", "貯"]
readings = ["チョウ", "ジョウ"]

[[useful]]
component = "刀, 刂"
used_in = ["召", "招", "沼", "昭", "紹", "詔", "超", "照"]
readings = ["ショウ"]

[[non-useful]]
component = "人"
used_in = ["仁"]
reason = "used in 1 kanji"

[[non-useful]]
component = "ニ"
used_in = ["仁", "弐"]
reason = "poor reading agreement."

# 3-Stroke
[[useful]]
component = "干"
used_in = ["刊", "汗", "肝", "軒", "幹", "岸"]
readings = ["カン"]

[[non-useful]]
component = "弓"
used_in = ["強", "窮"]
reason = "poor reading agreement."

# Before this point I was not tracking the not_useful_in tag. I should add it in sometime.

[[useful]]
component = "己"
used_in = ["起","記", "忌", "改", "紀"]
not_useful_in = ["妃"]
readings = ["キ"]

[[useful]]
component = "工"
used_in = ["功", "江", "攻", "空", "紅", "貢", "項", "控", "空"]
not_useful_in = ["恐"]
readings = ["ク", "クウ", "コウ"]

[[useful]]
component = "才"
used_in = ["在", "材", "財", "栽", "裁", "載"]
not_useful_in = []
readings = ["サイ", "ザイ"]

[[non-useful]]
component = "土"
used_in = ["仕"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "子"
used_in = ["字"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "勺"
used_in = ["的", "酌", "釣"]
reason = "Poor reading agreement."

[[useful]]
component = "小"
used_in = ["肖", "消", "硝"]
not_useful_in = ["削", "宵"]
readings = ["ショウ"]

[[non-useful]]
component = "寸"
used_in = ["村", "討"]
reason = "Poor reading agreement."

[[non-useful]]
component = "夕"
used_in = ["外"]
reason = "Only used in 1 kanji."

[[non-useful]]
component = "山"
used_in = ["仙"]
reason = "Only used in 1 kanji."

[[non-useful]]
component = "川"
used_in = ["訓"]
reason = "Only used in 1 kanji."

[[non-useful]]
component = "大"
used_in = ["泰", "達"]
reason = "Poor reading agreement."

[[useful]]
component = "土"
used_in = ["吐", "徒"]
not_useful_in = ["社"]
readings = ["ト"]

[[useful]]
component = "女"
used_in = ["奴", "努", "怒", "如"]
not_useful_in = []
readings = ["ド", "ジョ"]

# 4-Stroke
# p 132

[[useful]]
component = "王"
used_in = ["狂", "往", "皇"]
not_useful_in = []
readings = ["オウ", "コウ", "キョウ"]

[[useful]]
component = "戸"
used_in = ["雇", "顧"]
not_useful_in = ["所"]
readings = ["コ"]

[[useful]]
component = "五"
used_in = ["悟", "語"]
not_useful_in = []
readings = ["ゴ"]

[[non-useful]]
component = "午"
used_in = ["卸", "許", "御"]
reason = "Poor reading agreement."

[[useful]]
component = "月"
used_in = ["朝", "潮"]
not_useful_in = []
readings = ["チョウ"]

# p 134
[[useful]]
component = "斤"
used_in = ["近", "祈"]
not_useful_in = []
readings = ["キン", "キ"]

[[useful]]
component = "止"
used_in = ["市", "姉", "祉", "歯"]
not_useful_in = []
readings = ["シ"]

[[non-useful]]
component = "氏"
used_in = ["紙", "婚"]
reason = "poor reading agreement."

[[useful]]
component = "尺"
used_in = ["択", "沢", "釈", "訳"]
not_useful_in = ["駅"]
readings = ["タク", "シャク", "ヤク"]

[[useful]]
component = "井"
used_in = ["刑", "形", "型"]
not_useful_in = ["耕"]
readings = ["ケイ"]

[[non-useful]]
component = "升"
used_in = ["昇"]
reason = "Only used in 1 kanji."

[[useful]]
component = "中"
used_in = ["仲", "沖", "忠", "衷"]
not_useful_in = []
readings = ["チュウ"]

[[non-useful]]
component = "屯"
used_in = ["純 ", "鈍"]
reason = "Poor reading agreement"

# prime example of this book making the 
# worst choices over and over.
# 日 is listed as the radical even though
# it does not have the reading
# If you make the radical 冒 the analysis is perfect.
[[useful]]
component = "冒"
used_in = ["帽"]
not_useful_in = []
readings = ["ボウ"]

[[non-useful]]
component = "比"
used_in = ["階", "階"]
reason = "Poor reading agreement."

# No conceivable reason beyond historical interest that 父 should be considered the radical.
# 布 Should be the radical, but its still just not useful.
[[non-useful]]
component = "父"
used_in = ["布", "怖"]
reason = "Used in too few kanji."

# Habein Mathias uses 不 as this radical.
# This makes no sense. I am ignoring it, and using 咅 instead.
[[useful]]
component = "咅"
used_in = ["杯", "倍", "培", "陪","賠"]
not_useful_in = ["否", "杯","剖", "部"]
readings = ["ハイ", "バイ"]

[[useful]]
component = "方"
used_in = ["芳", "坊", "妨", "防", "放", "房", "肪", "訪", "倣", "傍"]
not_useful_in = []
readings = ["ボウ", "ホウ"]

[[non-useful]]
component = "毛"
used_in = ["耗"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "木"
used_in = ["新", "親", "薪"]
reason = "辛 is the informative analysis"

[[non-useful]]
component = "文"
used_in = ["蚊", "紋"]
reason = "Poor reading agreement"

[[non-useful]]
component = "予"
used_in = ["序", "野", "預"]
reason = "Poor reading agreement"

# 5 - stroke
[[useful]]
component = "甘"
used_in = ["勘", "敢", "堪"]
not_useful_in = ["紺", "厳"]
readings = ["カン"]

# 岬 only has readings matching the radical on incredibly rare words.
[[non-useful]]
component = "甲"
used_in = ["押", "岬"]
reason = "Poor reading agreement"

# 据 Is listed as using a radical derived from 古, but not 古 directly. These generally aren't helpful.
[[useful]]
component = "古"
used_in = ["居", "固", "故", "枯", "個", "湖"]
not_useful_in = ["苦", "箇"]
readings = ["コ"]

[[non-useful]]
component = "去"
used_in = ["却", "脚"]
reason = "Poor reading agreement"

[[non-useful]]
component = "示, 礻"
used_in = ["視"]
reason = "Only used in 1 kanji"

[[useful]]
component = "且"
used_in = ["助", "阻", "祖", "粗", "組", "租"]
not_useful_in = ["助", "査"]
readings = ["ソ", "ジョ"]

[[non-useful]]
component = "石"
used_in = ["拓"]
reason = "Only used in 1 kanji"

[[useful]]
component = "生"
used_in = ["姓", "性", "星", "牲"]
not_useful_in = []
readings = ["セイ"]


[[useful]]
component = "申"
used_in = ["伸", "神", "陣", "紳", "陳"]
not_useful_in = ["電"]
readings = ["シン", "ジン", "チン"]

# p 143
# The book mentions 往 but its radical is considered different
[[useful]]
component = "主"
used_in = ["注", "柱", "駐", "住"]
not_useful_in = [""]
readings = ["チュウ", "ジュウ"]

[[non-useful]]
component = "出"
used_in = ["拙"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "田"
used_in = ["細"]
reason = "Only used in 1 kanji"

# p 144
[[useful]]
component = "白"
used_in = ["伯", "拍", "泊", "迫", "舶"]
not_useful_in = [""]
readings = ["ハク"]

[[non-useful]]
component = "丙"
used_in = ["柄", "病"]
reason = "Phonetic is Exceptionally rare"

[[non-useful]]
component = "平"
used_in = ["坪", "評"]
reason = "Poor reading agreement"

[[non-useful]]
component = "北"
used_in = ["背"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "民"
used_in = ["眠", "婚"]
reason = "Poor reading agreement"

# p 144
[[useful]]
component = "予"
used_in = ["務", "務"]
not_useful_in = [""]
readings = ["ム"]

[[non-useful]]
component = "由"
used_in = ["抽", "宙", "届", "油", "笛", "軸"]
reason = "Poor reading agreement"

# p 146
[[non-useful]]
component = "用"
used_in = ["庸", "踊", "勇", "通", "痛"]
reason = "Poor reading agreement"

[[non-useful]]
component = "立"
used_in = ["粒"]
reason = "only used in 1 kanji"

[[useful]]
component = "衣"
used_in = ["依", "哀"]
not_useful_in = [""]
readings = ["イ", "アイ"]

# p147
[[useful]]
component = "交"
used_in = ["効", "郊", "校", "絞", "較"]
not_useful_in = [""]
readings = ["コウ"]

[[non-useful]]
component = "行"
used_in = ["衡"]
reason = "only used in 1 kanji"

[[non-useful]]
component = "舟"
used_in = ["受", "授", "朝", "潮"]
reason = "radical is not clear in the kanji"

# p 148
[[non-useful]]
component = "虫"
used_in = ["融"]
reason = "only used in 1 kanji"

[[useful]]
component = "兆"
used_in = ["挑", "逃", "桃", "眺", "跳"]
not_useful_in = [""]
readings = ["チョウ", "トウ"]

[[non-useful]]
component = "竹"
used_in = ["築", "篤"]
reason = "Poor reading agreement"

[[non-useful]]
component = "耳"
used_in = ["恥", "敢"]
reason = "Poor reading agreement"

[[non-useful]]
component = "米"
used_in = ["迷"]
reason = "Only used in 1 kanji"

[[useful]]
component = "羊"
used_in = ["洋", "祥", "詳", "様", "養", "窯"]
not_useful_in = [""]
readings = ["ヨウ", "ショウ"]

[[non-useful]]
component = "亜"
used_in = ["悪"]
reason = "Only used in 1 kanji"

[[useful]]
component = "求"
used_in = ["救", "救"]
not_useful_in = [""]
readings = ["キュウ"]

# p 150
[[non-useful]]
component = "車"
used_in = ["陣"]
reason = "Only used in 1 kanji"

[[useful]]
component = "辛"
used_in = ["親", "新", "薪"]
not_useful_in = [""]
readings = ["シン"]

[[non-useful]]
component = "臣"
used_in = ["姫"]
reason = "Only used in 1 kanji"

[[useful]]
component = "豆"
used_in = ["痘", "頭", "闘"]
not_useful_in = ["樹"]
readings = ["トウ"]

# p 151
[[non-useful]]
component = "足"
used_in = ["促"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "貝"
used_in = ["貞", "敗", "偵"]
reason = "Poor reading agreement"

[[useful]]
component = "良"
used_in = ["郎", "朗", "浪", "廊"]
not_useful_in = ["娘"]
readings = ["ロウ"]

# p 152
[[non-useful]]
component = "易"
used_in = ["賜"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "育"
used_in = ["充", "統", "銃"]
reason = "Questionable radical. Poor reading agreement"

[[useful]]
component = "京"
used_in = ["景", "鯨"]
readings = ["ケイ", "ゲイ"]

# Note: Habein and Mathias do not consider this a radical
# They consider it an instance of the 京 radical. But as it does not assist as a
# mnemonic device I have broken it out as a non-helpful radical.
[[non-useful]]
component = "景"
used_in = ["影"]
reason = "Only used in one kanji."

[[useful]]
component = "斉"
used_in = ["剤", "斎", "済"]
readings = ["サイ", "ザイ", "セイ"]

# p 153
[[useful]]
component = "長"
used_in = ["張", "帳", "脹"]
readings = ["チョウ"]

[[non-useful]]
component = "東"
used_in = ["凍", "陳", "棟", "練", "鍊", "欄"]
reason = "Poor reading agreement"

# p 154
[[useful]]
component = "非"
used_in = ["俳", "排", "悲", "扉", "輩"]
readings = ["ヒ", "ハイ"]

[[non-useful]]
component = "門"
used_in = ["間", "問"]
reason = "Poor reading agreement"

[[non-useful]]
component = "単"
used_in = ["禅", "弾", "戦"]
reason = "Poor reading agreement"

# p 155
[[non-useful]]
component = "献"
used_in = ["南"]
reason = "Only used in one kanji"

[[useful]]
component = "高"
used_in = ["豪", "稿", "橋", "矯"]
readings = ["コウ", "ごう", "キョウ"]

[[non-useful]]
component = "竜"
used_in = ["滝"]
reason = "Only used in one kanji"

[[non-useful]]
component = "魚"
used_in = ["漁"]
reason = "Only used in one kanji"

[[non-useful]]
component = "鳥"
used_in = ["島"]
reason = "Only used in one kanji"

# p 156
[[non-useful]]
component = "象"
used_in = ["像"]
reason = "Only used in one kanji"

[[useful]]
# Note: 急 is listed as using this radical.
# It is highly obscured so I won't count it even as a "not_useful_in"
component = "及"
used_in = ["吸", "級"]
readings = [""]
