# This document aims to be a complete list of all valuable phonetic kanji components sourced
# from Habein & Mathias' "The Complete Guide to Everyday Kanji." The book is a trove of information, 
# this seeks to distill it down to only the information useful to a student of Japanese.
# this list is very much a WORK IN PROGRESS and does not nearly cover everything, but I hope to complete the phonetic component at minimum.

#TEMPLATES
[[useful]]
component = ""
used_in = ["", "", ""]
not_useful_in = []
readings = [""]

[[non-useful]]
component = ""
used_in = ["", ""]
reason = ""

#  ____ _____  _    ____ _____    ___  _____   _     ___ ____ _____
# / ___|_   _|/ \  |  _ \_   _|  / _ \|  ___| | |   |_ _/ ___|_   _|
# \___ \ | | / _ \ | |_) || |   | | | | |_    | |    | |\___ \ | |
#  ___) || |/ ___ \|  _ < | |   | |_| |  _|   | |___ | | ___) || |
# |____/ |_/_/   \_\_| \_\|_|    \___/|_|     |_____|___|____/ |_|

# 1-Stroke
[[non-useful]]
component = "乙"
used_in = ["礼"]
reason = "only 1 kanji"

# 2-Stroke
[[useful]]
component = "又"
used_in = ["受", "授"]
readings = ["ジュ"]

[[non-useful]]
component = "九"
used_in = ["究, 軌"]
reason = "poor reading agreement."

[[useful]]
component = "七"
used_in = ["切", "窃"]
readings = ["セツ"]

[[non-useful]]
component = "十"
used_in = ["汁", "針"]
reason = "poor reading agreement"

[[useful]]
component = "丁"
used_in = ["庁", "成", "町", "亭", "頂", "城", "盛", "貯"]
readings = ["チョウ", "ジョウ"]

[[useful]]
component = "刀, 刂"
used_in = ["召", "招", "沼", "昭", "紹", "詔", "超", "照"]
readings = ["ショウ"]

[[non-useful]]
component = "人"
used_in = ["仁"]
reason = "used in one kanji"

[[non-useful]]
component = "ニ"
used_in = ["仁", "弐"]
reason = "poor reading agreement."

# 3-Stroke
[[useful]]
component = "干"
used_in = ["刊", "汗", "肝", "軒", "幹", "岸"]
readings = ["カン"]

[[non-useful]]
component = "弓"
used_in = ["強", "窮"]
reason = "poor reading agreement."

# Before this point I was not tracking the not_useful_in tag. I should add it in sometime.

[[useful]]
component = "己"
used_in = ["起","記", "忌", "改", "紀"]
not_useful_in = ["妃"]
readings = ["キ"]

[[useful]]
component = "工"
used_in = ["功", "江", "攻", "空", "紅", "貢", "項", "控", "空"]
not_useful_in = ["恐"]
readings = ["ク", "クウ", "コウ"]

[[useful]]
component = "才"
used_in = ["在", "材", "財", "栽", "裁", "載"]
not_useful_in = []
readings = ["サイ", "ザイ"]

[[non-useful]]
component = "土"
used_in = ["仕"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "子"
used_in = ["字"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "勺"
used_in = ["的", "酌", "釣"]
reason = "Poor reading agreement."

[[useful]]
component = "小"
used_in = ["肖", "宵", "消", "硝"]
not_useful_in = ["削"]
readings = [""]

[[non-useful]]
component = "寸"
used_in = ["村", "討"]
reason = "Poor reading agreement."

[[non-useful]]
component = "夕"
used_in = ["外"]
reason = "Only used in one kanji."

[[non-useful]]
component = "山"
used_in = ["仙"]
reason = "Only used in one kanji."

[[non-useful]]
component = "川"
used_in = ["訓"]
reason = "Only used in one kanji."

[[non-useful]]
component = "大"
used_in = ["泰", "達"]
reason = "Poor reading agreement."

[[useful]]
component = "土"
used_in = ["吐", "徒"]
not_useful_in = ["社"]
readings = ["ト"]

[[useful]]
component = "女"
used_in = ["奴", "努", "怒", "如"]
not_useful_in = []
readings = ["ド", "ジョ"]

# 4-Stroke
# p 132