# This document aims to be a complete list of all valuable phonetic kanji components sourced
# from Habein & Mathias' "The Complete Guide to Everyday Kanji." The book is a trove of information, 
# this seeks to distill it down to only the information useful to a student of Japanese.
# this list is very much a WORK IN PROGRESS and does not nearly cover everything, but I hope to complete the phonetic component at minimum.

#TEMPLATES
# [[useful]]
# component = ""
# used_in = ["", "", ""]
# not_useful_in = []
# readings = [""]

# [[non-useful]]
# component = ""
# used_in = ["", ""]
# reason = ""

#  ____ _____  _    ____ _____    ___  _____   _     ___ ____ _____
# / ___|_   _|/ \  |  _ \_   _|  / _ \|  ___| | |   |_ _/ ___|_   _|
# \___ \ | | / _ \ | |_) || |   | | | | |_    | |    | |\___ \ | |
#  ___) || |/ ___ \|  _ < | |   | |_| |  _|   | |___ | | ___) || |
# |____/ |_/_/   \_\_| \_\|_|    \___/|_|     |_____|___|____/ |_|

# 1-Stroke
[[non-useful]]
component = "乙"
used_in = ["礼"]
reason = "only 1 kanji"

# 2-Stroke
[[useful]]
component = "又"
used_in = ["受", "授"]
readings = ["ジュ"]

[[non-useful]]
component = "九"
used_in = ["究, 軌"]
reason = "poor reading agreement."

[[useful]]
component = "七"
used_in = ["切", "窃"]
readings = ["セツ"]

[[non-useful]]
component = "十"
used_in = ["汁", "針"]
reason = "poor reading agreement"

[[useful]]
component = "丁"
used_in = ["庁", "成", "町", "亭", "頂", "城", "盛", "貯"]
readings = ["チョウ", "ジョウ"]

[[useful]]
component = "刀, 刂"
used_in = ["召", "招", "沼", "昭", "紹", "詔", "超", "照"]
readings = ["ショウ"]

[[non-useful]]
component = "人"
used_in = ["仁"]
reason = "used in one kanji"

[[non-useful]]
component = "ニ"
used_in = ["仁", "弐"]
reason = "poor reading agreement."

# 3-Stroke
[[useful]]
component = "干"
used_in = ["刊", "汗", "肝", "軒", "幹", "岸"]
readings = ["カン"]

[[non-useful]]
component = "弓"
used_in = ["強", "窮"]
reason = "poor reading agreement."

# Before this point I was not tracking the not_useful_in tag. I should add it in sometime.

[[useful]]
component = "己"
used_in = ["起","記", "忌", "改", "紀"]
not_useful_in = ["妃"]
readings = ["キ"]

[[useful]]
component = "工"
used_in = ["功", "江", "攻", "空", "紅", "貢", "項", "控", "空"]
not_useful_in = ["恐"]
readings = ["ク", "クウ", "コウ"]

[[useful]]
component = "才"
used_in = ["在", "材", "財", "栽", "裁", "載"]
not_useful_in = []
readings = ["サイ", "ザイ"]

[[non-useful]]
component = "土"
used_in = ["仕"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "子"
used_in = ["字"]
reason = "Only used in 1 kanji"

[[non-useful]]
component = "勺"
used_in = ["的", "酌", "釣"]
reason = "Poor reading agreement."

[[useful]]
component = "小"
used_in = ["肖", "宵", "消", "硝"]
not_useful_in = ["削"]
readings = [""]

[[non-useful]]
component = "寸"
used_in = ["村", "討"]
reason = "Poor reading agreement."

[[non-useful]]
component = "夕"
used_in = ["外"]
reason = "Only used in one kanji."

[[non-useful]]
component = "山"
used_in = ["仙"]
reason = "Only used in one kanji."

[[non-useful]]
component = "川"
used_in = ["訓"]
reason = "Only used in one kanji."

[[non-useful]]
component = "大"
used_in = ["泰", "達"]
reason = "Poor reading agreement."

[[useful]]
component = "土"
used_in = ["吐", "徒"]
not_useful_in = ["社"]
readings = ["ト"]

[[useful]]
component = "女"
used_in = ["奴", "努", "怒", "如"]
not_useful_in = []
readings = ["ド", "ジョ"]

# 4-Stroke
# p 132

[[useful]]
component = "王"
used_in = ["狂", "往", "皇"]
not_useful_in = []
readings = ["オウ", "コウ", "キョウ"]

[[useful]]
component = "戸"
used_in = ["雇", "顧"]
not_useful_in = ["所"]
readings = ["コ"]

[[useful]]
component = "五"
used_in = ["悟", "語"]
not_useful_in = []
readings = ["ゴ"]

[[non-useful]]
component = "午"
used_in = ["卸", "許", "御"]
reason = "Poor reading agreement."

[[useful]]
component = "月"
used_in = ["朝", "潮"]
not_useful_in = []
readings = ["チョウ"]

# p 134
[[useful]]
component = "斤"
used_in = ["近", "祈"]
not_useful_in = []
readings = ["キン", "キ"]

[[useful]]
component = "止"
used_in = ["市", "姉", "祉", "歯"]
not_useful_in = []
readings = ["シ"]

[[non-useful]]
component = "氏"
used_in = ["紙", "婚"]
reason = "シ"

[[useful]]
component = "尺"
used_in = ["択", "沢", "釈", "訳"]
not_useful_in = ["駅"]
readings = ["タク", "シャク", "ヤク"]

[[useful]]
component = "井"
used_in = ["刑", "形", "型"]
not_useful_in = ["耕"]
readings = ["ケイ"]

[[non-useful]]
component = "升"
used_in = ["昇"]
reason = "Only used in one kanji."

[[useful]]
component = "中"
used_in = ["仲", "沖", "忠", "衷"]
not_useful_in = []
readings = ["チュウ"]

[[non-useful]]
component = "屯"
used_in = ["純 ", "鈍"]
reason = "Poor reading agreement"

# prime example of this book making the 
# worst choices over and over.
# 日 is listed as the radical even though
# it does not have the reading
# If you make the radical 冒 the analysis is perfect.
[[useful]]
component = "冒"
used_in = ["帽"]
not_useful_in = []
readings = ["ボウ"]

[[non-useful]]
component = "比"
used_in = ["階", "階"]
reason = "Poor reading agreement."

# No conceivable reason beyond historical interest that 父 should be considered the radical.
# 布 Should be the radical, but its still just not useful.
[[non-useful]]
component = "父"
used_in = ["布", "怖"]
reason = "Used in too few kanji."

# Habein Mathias uses 不 as this radical.
# This makes no sense. I am ignoring it, and using 咅 instead.
[[useful]]
component = "咅"
used_in = ["杯", "倍", "培", "陪","賠"]
not_useful_in = ["否", "杯","剖", "部"]
readings = ["ハイ", "バイ"]

[[useful]]
component = "方"
used_in = ["芳", "坊", "妨", "防", "放", "房", "肪", "訪", "倣", "傍"]
not_useful_in = []
readings = ["ボウ", "ホウ"]
